### ISSUE TITLE
Colors are inverted and touchscreen not pressing

### ISSUE THREAD

**Issue by YouHusam** [Vasily-Kapustin/ti9488#1]
Hi, thank you so much for this, I managed to get it to work I am having the following problems:

1. The colors are inverted, I tried to add `bgr = <0>;` as suggested some places online to the dts file, but it didn't help.
2. The touchscreen seems to work only for pointing, but not clicking. Schematic on AliExpress page says it's using ADS7843, not sure if it causes it.

```
klipper@mainsailos:~ $ uname -a
Linux mainsailos 6.6.51-v8+ #1799 SMP PREEMPT Thu Sep 26 16:11:55 BST 2024 aarch64 GNU/Linux

klipper@mainsailos:~ $ DISPLAY=:0 xrandr
Screen 0: minimum 320 x 200, current 480 x 320, maximum 480 x 320
Unknown19-1 connected primary 480x320+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   480x320        0.01*+

klipper@mainsailos:~ $ DISPLAY=:0 xinput list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ ADS7846 Touchscreen                       id=6    [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
klipper@mainsailos:~ $ DISPLAY=:0 xinput list-props 6
Device 'ADS7846 Touchscreen':
        Device Enabled (122):   1
        Coordinate Transformation Matrix (123): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Accel Profile (246):     0
        Device Accel Constant Deceleration (247):       1.000000
        Device Accel Adaptive Deceleration (248):       1.000000
        Device Accel Velocity Scaling (249):    10.000000
        Device Product ID (250):        0, 7846
        Device Node (251):      "/dev/input/event0"
        Evdev Axis Inversion (252):     0, 0
        Evdev Axis Calibration (253):   0, 4095, 0, 4095
        Evdev Axes Swap (254):  0
        Axis Labels (255):      "Abs X" (243), "Abs Y" (244), "Abs Pressure" (245)
        Button Labels (256):    "Button Unknown" (242), "Button Unknown" (242), "Button Unknown" (242), "Button Wheel Up" (128), "Button Wheel Down" (129)
        Evdev Scrolling Distance (257): 0, 0, 0
        Evdev Middle Button Emulation (258):    0
        Evdev Middle Button Timeout (259):      50
        Evdev Middle Button Button (260):       2
        Evdev Third Button Emulation (261):     0
        Evdev Third Button Emulation Timeout (262):     1000
        Evdev Third Button Emulation Button (263):      3
        Evdev Third Button Emulation Threshold (264):   20
        Evdev Wheel Emulation (265):    0
        Evdev Wheel Emulation Axes (266):       0, 0, 4, 5
        Evdev Wheel Emulation Inertia (267):    10
        Evdev Wheel Emulation Timeout (268):    200
        Evdev Wheel Emulation Button (269):     4
        Evdev Drag Lock Buttons (270):  0
```

A 3.2" display that uses ili9340 works well using waveshare32b dts

I would like to suggest to add info about using [rpi source](https://github.com/RPi-Distro/rpi-source) to get kernel sources, I struggled when trying to get it to compile.

Thank you so much again.

**Comment by Vasily-Kapustin** [comment]
Hey, I haven't worked on this project in a bit, though I can still try to help.

The good news is that the ads7843 and ads7846 can both be controlled using the same driver ads7846 driver. I believe their initializations maybe a little different in the device tree overlay. You can try to change the settings in [here](https://github.com/Vasily-Kapustin/ti9488/blob/6bf6f6afb28186a7a6a97269245bf2506e8878c2/rpi-overlays/generictft-9488-overlay.dts#L64C25-L64C45) or in your boot config file.
Are you able to read any events from the touchscreen? The dts file will initialize the touchscreen to be a pointer device but if it is not set up correctly it will produce no events. I never got this issue resolved myself after hours of testing. The ads7846 is part of the raspberrypi/linux distro if you want to search for it.  

As to the inverted colors issue:
- Are you seeing the output you want on your screen / do you make it past boot?
- What type of color inversion is it? Picture may be helpful
- The aliexpress link to your display could also be helpful

Im also a bit unclear as to what "A 3.2" display that uses ili9340 works well using waveshare32b dts" means.

**Comment by YouHusam** [comment]
Thank you for the quick reply, sorry if I'm not very clear, it's late at night and this thing is driving me crazy.
to answer your questions:
1. yes, xserver starts normally, the screen is on, and displaying what I want, the colors are inverted as in black is white, red is cyan, green is purple and blue is yellow, 
2. attached
3. It's an IPS display with not much documentation https://www.aliexpress.com/item/1005004765008440.html I didn't know it will be a pain to get it to work with the pi when I bought it. it might be this  http://www.lcdwiki.com/3.5inch_SPI_Module_ILI9488_SKU:MSP3520 though I'm not sure

Changing the driver in the dts file fixed the touch issue, thanks a lot, apparently I was compiling the wrong project and was wondering why it didn't work before 😅

I meant a smaller 3.2 inches touchscreen display with ili9340 chip that I'm using https://github.com/swkim01/waveshare-dtoverlays to edit the overlays so I can change the pinout, you can see it in the first picutre attached
![20241003_020215](https://github.com/user-attachments/assets/66b72085-e8a5-40d6-a365-37eab8ea053f)

![20241003_021907](https://github.com/user-attachments/assets/4dd9a63c-25c4-4f71-9a19-3eb0373a13be)

![20241003_024947](https://github.com/user-attachments/assets/0869e7c0-91b9-4a21-bb7f-69b7a6be4333)

**Comment by YouHusam** [comment]
Adding more info for future reference:
touch screen was hard to get to work properly, calibration was always off, here's what I did to fix it:
1. In `/etc/X11/xorg.conf.d/99-calibration.conf` I removed `Option "Calibration" ...`, set `Option  "SwapAxes"      "1"` and `Option "InvertY" "1"`
2. Run `DISPLAY=:0 xinput_calibrator`
3. Copy the output and remove `Option "InvertY" "1"`

This got my touchscreen to work properly with all the axes pressing in the right places

**Comment by YouHusam** [comment]
IT WORKS!!
I followed the instructions in this issue https://github.com/birdtechstep/tinydrm/issues/3 adding `	mipi_dbi_command(dbi, ILI9488_CMD_DISP_INVERSION_ON);` to line 391 fixed it for me

![20241003_052852](https://github.com/user-attachments/assets/bb7c353b-d425-482a-80cd-4973e1f53555)

Display quality is bad and colors are not accurate, I'm getting image retention, not sure if it's software issue or hardware. I will check later with a microcontroller to see if things look different.

Thank you very much for your work!

**Comment by Vasily-Kapustin** [comment]
I'm glad you got it working! 
Thank you for sharing the steps to make the touchscreen functional, I'll check them out at some point.
